development: &defaults
  # These are the settings for repository :default
  adapter:  mysql
  database: highguard_merb_dev
  encoding: utf8
  username: root
  password: 
  host:     localhost

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgresql
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

rake:
  <<:       *defaults
  database: highguard_merb_dev

  # repositories:
  #   repo1:
  #     database: sample_development
    
    
test:
  <<:       *defaults
  database: highguard_merb_test

  # repositories:
  #   repo1:
  #     database: sample_development

production:
  <<:       *defaults
  database: golb_production

  # repositories:
  #   repo1:
  #     database: sample_development